language: python
python:
- '3.5'
- '3.6'
- 3.7-dev
install:
- sudo find /usr -name '*.pyc' -delete
- sudo apt update
- pip install .
- python setup.py install
- pip install pytest
- pip install coveralls
- pip install pytest-cov
script:
- coverage run --source=./chunkflow chunkflow generate-task
- coverage run --source=./chunkflow chunkflow create-chunk -o seg create-chunk -o
  gt evaluate-segmentation -s seg -g gt
- coverage run -a --source=./chunkflow chunkflow create-chunk write-h5 --file-name=/tmp/img.h5
- if test -f /tmp/img.h5 ; then echo "File found"; else exit 1; fi
- coverage run -a --source=./chunkflow chunkflow read-h5 --file-name=/tmp/img.h5
- coverage run -a --source=./chunkflow chunkflow create-chunk --size 36 448 448 inference
  --framework identity --batch-size 3 cloud-watch --log-name chunkflow-test
- pytest --cov-append --cov=./chunkflow ./tests --verbose
after_success:
- coveralls
deploy:
  provider: pypi
  user: jingpengw
  password:
    secure: CZ6IGaVJX+nSZ2mb9U4VMo72ivjtlMQpWONM+VkmbcS85bqAcX58cjaEoD1cZd2e2Bpf6BZVfq+K5BE7I1GsSzQDCFDmT3xRqDLtwF/9S9PU9OfQfbgwuH7kjDMQu9K5e5M8+/JTTECjeU3e7uwskJrdf6qg6vNzcoyhZi6mTR4K0g9hq12eaPYAx07ZoBTJzO8dM7mhLA9IsNGAc7PjSpuwbLy1kzWN+icLZiYnMcVs3FCCSN5Xegyye0h74Mc3n3kopOQiVLXTRTlYlQm9Y3SHp5tRcsCm2/2g/lKaJRsQlncZMd91s01fkJv6TWUXZR3NyxefQUNhB/rQeNIeGc81ppWN2DCmcrDWoQw7sA/B63M0u5Oaw5uvu7u+zF3QDjMe+1MgxA9AxQkno4X6h1xXBuMViSmoyP+mhyJiN8clQYO4wHGyc0VMi7W0o+YWn7jiUZxy8VHAD1FAsBGi3URIpvErODeNbQsDciaZiixA/3pvrSeN3JdMQqtQ5gzqegB3arVetupXbmyk0jmCIUEAxfw3KC+6kURVWNGW7M0p7A6QPo6H4tXtopMGK2MRc/deRfSo6LjHrmGK16QdEdPAaieuWRVbHDjoAXyUxQlGB91v4Rk04/aS7vu5xurrJGp35VPRavRpg5vKPzEPPPi7UHCjQfo4bUYBainUzw8=
  on:
    tags: true
  distributions: sdist bdist_wheel
