language: python 
python:
- '3.5'
- '3.6'
- '3.7'

install:
- pip install --upgrade pip 
- pip install numpy --no-cache-dir  
- pip install fpzip --no-binary :all: --no-cache-dir 
- pip install -r requirements.txt; 

script:
- python3 -m unittest 

