language: python 
python:
- '3.5'
- '3.6'
- '3.7-dev'

install:
    - pip install --upgrade pip
    # fix fpzip problem
    - pip install numpy==1.16
    # fix neuroglancer problem
    - pip install tornado==5.0
    - pip install fpzip
    - pip install -r requirements.txt
    - pip install -e .  

before_script:
    - pip install coveralls

script:
    - cd chunkflow
    # use -a to append to the coverage file, otherwise it will clean previous record
    - coverage run -a --source=chunkflow consume_tasks.py create-chunk write-h5 --file-name /tmp/test.h5
    - coverage run -a --source=chunkflow -m unittest

after_success:
- coveralls 

matrix:
  allow_failures:
  - python: '3.7-dev'
