language: python 
python:
- '3.5'
- '3.6'
- '3.7-dev'

install:
- pip install --upgrade pip
- pip install numpy==1.16
- pip install fpzip
- pip install -r requirements.txt
- pip install -e .  

before_script:
- pip install coveralls

script:
- cd chunkflow
- coverage run --source=chunkflow -m unittest
# use -a to append to the coverage file, otherwise it will clean previous record
- coverage run -a consume_tasks.py create-chunk write-h5 --file-name /tmp/test.h5

after_success:
- coveralls 

matrix:
  allow_failures:
  - python: '3.7-dev'
