apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference 
  labels: 
    app: chunkflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chunkflow
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailabe: 100%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: chunkflow
    spec:
      hostNetwork: true
      containers:
      - name: chunkflow
        image: my/image/path
        imagePullPolicy: Always
        command: ["/bin/bash", "-c", "--"]
        args: ["source /root/.bashrc; ",
                "mkdir /nets; cd /nets; ",
                "wget https://storage.googleapis.com/microns-seunglab/minnie_v0/minnie10/affinitymap/test/model230000.chkpt",
                "export PYTHONPATH=/root/chunkflow:/root/pytorch-model:/root/pytorch-emvision:/root/cloud-volume:$PYTHONPATH",
                "python3 /root/chunkflow/scripts/consume_tasks.py --image-layer-path='path/of/image' --output-layer-path='path/of/output' --convnet-model-path='path/of/net' --convnet-weight-path='path/of/net' --queue-name chunkflow --patch-size 20 256 256 --patch-overlap 4 64 64 --cropping-margin-size 4 64 64 --output-key affinity --num-output-channels 3 --mip 1 --framework pytorch-multitask --image-validate-mip 5 --visibility-timeout 1800 --proc-num 2 --interval 300",]
        # this is very helpful for debuging
        # we can run kubectl exec pod-it -it /bin/bash 
        # to login the pod and try different commands
        #args: ["sleep infinity"]
        volumeMounts:
        - name: secrets 
          mountPath: /root/.cloudvolume/secrets 
          readOnly: true
        env:
        - name: PYTHONPATH
          value: /root/chunkflow:/root/pytorch-model:/root/pytorch-emvision:/root/cloud-volume:$PYTHONPATH
        - name: LC_ALL 
          value: C.UTF-8 
        - name: LANG 
          value: C.UTF-8 
        resources:
          limits:
            cpu: "3"
            memory: 23G
            nvidia.com/gpu: 1
      volumes:
      - name: secrets 
        secret: 
          secretName: secrets

